language: python

cache: pip

jobs:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35

    - os: linux
      python: 3.6
      env: TOXENV=py36

    - os: linux
      python: 3.7
      env: TOXENV=py37

    - os: linux
      python: 3.8
      env: TOXENV=py38

    - os: linux
      python: 3.9-dev
      env: TOXENV=py39

    - os: linux
      python: pypy3
      env: TOXENV=pypy3

    - os: osx
      language: generic
      env: TOXENV=py37

  allow_failures:
    - os: linux
      python: 3.5
      env: TOXENV=py35

install:
  - travis_retry bash -x .travis/install.sh

script:
  - tox
